M48
; DRILL file {KiCad 9.0.3} date 2025-12-22T17:44:07-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-22T17:44:07-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.300
%
G90
G05
T1
X110.25Y-68.0
T2
X102.76Y-68.0
M30
