M48
; DRILL file {KiCad 9.0.3} date 2025-10-30T20:26:16-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-30T20:26:16-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.300
%
G90
G05
T1
X79.01Y-71.5
T2
X71.52Y-71.5
M30
